[config]
# Path of output directory relative to workspace
output = "blogs/out"
# Path of input Markdown
input = "blogs/md"

# More about these can be found in pulldown-cmark's documentation
[markdown]
# Enable tables in Markdown
tables = true
# Enable footnotes in Markdown
footnotes = true
# Enable strikethrough in Markdown
strikethrough = true
# Enable tasklists in Markdown
tasklists = true
# Enable smart punctuation in Markdown
smart_punctuation = true
# Enable heading attributes in Markdown
heading_attributes = true

[[articles]]
title = "Test"
description = "Dedicated to testing blog features"
infile = "test.md"
outfile = "test.html"
card = "https://www.responsivetranslation.com/wp-content/uploads/2016/05/exam.jpg"
thumbnail = "https://www.responsivetranslation.com/wp-content/uploads/2016/05/exam.jpg"

[[articles]]
title = "Custom Assembler"
description = "Creating an assembler for a custom CPU architecture"
infile = "assembler.md"
outfile = "assembler.html"
card = "https://isaaccomputerscience.org/api/v3.5.0/api/images/content/computer_science/computer_systems/programming_languages/figures/isaac_cs_sys_proglang_simulator_display_if.png"
thumbnail = "https://www.pagetable.com/docs/cbmasm/resident_assembler.png"
next = { title = "CPU Emulator", href = "emulator.html" }

[[articles]]
title = "CPU Emulator"
description = "Creating an emulator for my custom CPU"
infile = "emulator.md"
outfile = "emulator.html"
card = "https://cdn.hackaday.io/images/5525451542686847623.png"
thumbnail = "https://cdn.hackaday.io/images/5525451542686847623.png"
prev = { title = "Custom Assembler", href = "assembler.html" }
